language: python

sudo: true

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.5"
  - "3.6"

env:
  # test new (conda>=4.4) and old-style conda installs
  - CONDA_4_4_STYLE=false
  - CONDA_4_4_STYLE=true

install:
  - sudo apt-get update
  - sudo apt-get install -y libfreetype6-dev libfontconfig1-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - if [ "$CONDA_4_4_STYLE" = "true" ]; then
      . $HOME/miniconda/etc/profile.d/conda.sh
    else
      export PATH="$HOME/miniconda/bin:$PATH"
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes --quiet conda
  # get 4.6 from canary (can revert to 'conda' when released)
  - conda install -n root conda-canary::conda=4.6 conda-env anaconda-client notebook
  - conda info -a
  - conda create -n nb_conda_kernels python=$TRAVIS_PYTHON_VERSION
  - conda install -n nb_conda_kernels -c conda-forge --file requirements.txt
  - if [ "$CONDA_4_4_STYLE" = true ]; then
      conda activate nb_conda_kernels
    else
      source activate nb_conda_kernels
    fi
  - pip install python-coveralls
  - npm install
  - conda list
  - npm list

script:
  - pip install -e .
  - python -m nb_conda_kernels.install --enable --prefix="${CONDA_PREFIX}"
  - npm run test

after_success:
  - coveralls
