{% set data = load_setup_py_data() %}

package:
  name: nb_conda_kernels
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - jupyter_client >=4.2
    - jupyter_core
    - traitlets
    - psutil

test:
  source_files:
    - setup.cfg
    - tests
  requires:
    - pytest
    - pytest-cov
    - ipykernel
    - notebook <7
    - requests
    - mock
  commands:
    - pip check
    - python -m nb_conda_kernels list
    - python -m pytest -v --cov=nb_conda_kernels tests

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Launch Jupyter kernels for any installed conda environment.'
