package:
  name: nb_conda_kernels
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  script_env:
   - ANE_RELEASE
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{% if environ.get('ANE_RELEASE', '0') == '1' %}0{% else %}{{ environ.get('GIT_BUILD_STR', '0') }}{% endif %}

requirements:
  build:
    - python
  run:
    - python
    - notebook
    - traitlets >=4.1.0

test:
  requires:
    - notebook
    - python
    - requests
    - nose
    - selenium

source:
  git_url: ../

about:
  home: https://github.com/Anaconda-Server/nb_conda_kernels
  license: BSD
