package:
  name: nb_conda_kernels
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - python
  run:
    - python
    - notebook
    - traitlets >=4.1.0

test:
  requires:
    - notebook
    - python
    - requests
    - nose
    - selenium

source:
  {% if environ.get('ANE_NO_GIT_URL', '0') == '1' %}path: ../
  {% else %}git_url: ../{% endif %}

about:
  home: https://github.com/Anaconda-Server/nb_conda_kernels
  license: BSD
