package:
  name: nb_conda_kernels
  version: "0.1.2"

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '0') }}
  script_env:
   - ANE_RELEASE

requirements:
  build:
    - python
  run:
    - python
    - notebook
    - traitlets >=4.1.0

test:
  requires:
    - notebook
    - python
    - requests
    - nose
    - selenium

source:
  {% if environ.get('ANE_RELEASE', '0') == '1' %}path: ../
  {% else %}git_url: ../{% endif %}

about:
  home: https://github.com/Anaconda-Server/nb_conda_kernels
  license: BSD
